name: OpenAI to Z Auto Pipeline

defaults:
  run:
    working-directory: Z2interpreter

on:
  push:
    branches: [main]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set Git Identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Run pipeline
        run: python run_pipeline.py

      - name: Commit & Push results
        run: |
          git add .
          git diff --cached --quiet || git commit -m "🤖 Auto update via GitHub Actions"
          git push
